### ISSUE TITLE
[Bug]: TypeError("Client.init() got an unexpected keyword argument 'proxies'")

### ISSUE THREAD

**Issue by store-x** [DavideGalilei/gpytranslate#27]
### What happened?

when i ran this simple code:
```py
import traceback
from gpytranslate import SyncTranslator
def translate_text(text: str, tr_lang: str):
    if not text or not tr_lang:
        raise ValueError("Text and target language are required")
    try:
        t = SyncTranslator()
        translation = t.translate(text=text, sourcelang='en', targetlang=tr_lang)
        return translation.text
    except Exception as e:
        traceback.print_exc()
        print(f"Sync translation failed: {e}")
        return text
    
print(translate_text('hello', 'hi'))
```
I got an unexpected error:
```
Traceback (most recent call last):
  File "", line 9, in translate_text
  File "/usr/local/lib/python3.10/site-packages/gpytranslate/sync/sync_translator.py", line 152, in translate
    raise TranslationError(e) from None
gpytranslate.exceptions.TranslationError: An error occurred while trying to translate/tts: TypeError("Client.init() got an unexpected keyword argument 'proxies'")
```

### OS / Environment

Linux my-hostname 6.8.0-1018-aws #19~22.04.1-Ubuntu SMP Wed Oct  9 16:48:22 UTC 2024 x86_64 GNU/Linux

 with python 3.10.4, most recent version of gpytranslate

### Traceback

```python-traceback
Traceback (most recent call last):
  File "", line 9, in translate_text
  File "/usr/local/lib/python3.10/site-packages/gpytranslate/sync/sync_translator.py", line 152, in translate
    raise TranslationError(e) from None
gpytranslate.exceptions.TranslationError: An error occurred while trying to translate/tts: TypeError("Client.init() got an unexpected keyword argument 'proxies'")
```

### Searched before submitting

- [X] I searched for duplicates, and didn't found anything.
- [X] I searched this bug on a search engine, and didn't found anything.

**Comment by DavideGalilei** [comment]
@store-x can you try the version 2.0.0 of the library?
`pip install -U gpytranslate`

If the issue persists, let me know, and feel free to reopen this issue.

**Comment by DavideGalilei** [comment]
Update 2.0.0: https://github.com/DavideGalilei/gpytranslate/commit/a24860101d2f08dd502c5626331e313b87982028
